### ISSUE TITLE
error when `import streetview`

### ISSUE THREAD

**Issue by Yingjie4Science** [sk-zk/streetlevel#1]
Hi! When I run `from streetlevel import streetview`, I saw this error. Could you help? I am using Python3.9, it seems "|" only works in Python3.10?

> File "C:\Users\pc\AppData\Roaming\Python\Python39\site-packages\streetlevel\streetview\streetview.py", line 105, in <module>
>     locale: str = "en", session: Session = None) -> StreetViewPanorama | None:
> 
> TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by sk-zk** [comment]
[Looks like it](https://peps.python.org/pep-0604/), I wasn't aware of that. I'm going to change those to `Union` for 3.8/3.9 compatibility

**Comment by sk-zk** [comment]
Fixed d018f62
