### ISSUE TITLE
Error on lookaround.to_equirectangular

### ISSUE THREAD

**Issue by tassilo-net** [sk-zk/streetlevel#14]
Hi, i have tested your code sample from [https://streetlevel.readthedocs.io/en/master/streetlevel.lookaround.html#streetlevel.lookaround.reproject.to_equirectangular](url)

But i have an error when i use lookaround.to_equirectangular:

`File "/usr/local/lib/python3.11/dist-packages/streetlevel/lookaround/reproject.py", line 35, in to_equirectangular
    full_width = round(faces[0].width * (1024 / 5632)) * 16
                       ^^^^^^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'width'`

Can you help me?

**Comment by sk-zk** [comment]
The function `to_equirectangular()` takes a list of PIL images. 

If the `bytes` in question are the original HEIC file, you must first decode it with a library of your choice, such as [pillow_heif](https://pypi.org/project/pillow-heif/), which comes with a PIL plugin.

**Comment by tassilo-net** [comment]
Thank you. I missed that.
I have pillow-heif installed, but I'm having trouble writing the correct code. Do you have a code snippet that would do the trick?

**Comment by sk-zk** [comment]
```python
from PIL import Image
from pillow_heif import register_heif_opener
import io

register_heif_opener()

(...)

face = Image.open(io.BytesIO(face_heic))
```

**Comment by tassilo-net** [comment]
Thank you. I had `bytes(` instead of `io.BytesIO(`
