### ISSUE TITLE
Street View Photo Paths?

### ISSUE THREAD

**Issue by upintheairsheep** [sk-zk/streetlevel#15]
Google Street View supports viewing 2D images on the map, and navigating between them. The feature was removed, but you can still view these. They have special tags to show what direction the image is facing, and no mention of photo paths are in the documentation.

**Comment by sk-zk** [comment]
Photo paths won't be supported, sorry. Google discontinued the feature a year ago, so the data is getting increasingly stale, and there was never all that much of it anyway - Mapillary, KartaView, Mapilio, and Panoramax are better sources for this type of imagery.
