### ISSUE TITLE
heading of panorama

### ISSUE THREAD

**Issue by JHT7** [sk-zk/streetlevel#17]
Hello! I'd like to ask if there's a way to change the heading of a panorama? 
Or if there's a way to know the heading of a downloaded panorama (like, which direction the center of the image is facing). 
Thank you!

**Comment by sk-zk** [comment]
The heading of a panorama is found in the `heading` field of the panorama object. It is always given in radians, but the value which is represented by 0 and whether it goes CW or CCW depends on the service; check the documentation for the respective service for this.

**Comment by JHT7** [comment]
Hello! Apologies for the delayed response. I've reviewed the information, and I understand it now. I wanted to ask if there's a way to achieve those two scenarios I mentioned using the code you provided. Thank you!

**Comment by sk-zk** [comment]
I already explained the latter to you, and as for the former: if the panorama is equirectangular, you should be able to just shift the image horizontally. Not sure what the use case for that would be though since pretty much all panorama renderers can apply the heading offset nondestructively.
