### ISSUE TITLE
Any limitations on the number of requests to find_panorama and download_panorama

### ISSUE THREAD

**Issue by happyday521** [sk-zk/streetlevel#18]
Hi，

Thanks for your great work!
I want to use the following code：
```
for (lat, lon) in crawl_list:
    pano = streetview.find_panorama(lat, lon)
    streetview.download_panorama(pano, f"{pano.id}.jpg")
```
to Batch Crawling streetview images from google map, but I am concerned about any restrictions on accessing this service. Are there any limitations on the number of requests or the frequency of access to this function? 
Thanks!

**Comment by sk-zk** [comment]
There are no limitations that I'm aware of. I've made loads of requests in the past and have never been throttled or blocked.
