### ISSUE TITLE
feature request: Streetside bbox to slippy map tiles

### ISSUE THREAD

**Issue by ChemicalNRG** [sk-zk/streetlevel#19]
If Bing Streetside also works with slippy map tiles (with the same z height), shouldn't it be fairly easy to use the bbox request of Streetside to get the slippy map tiles and with that the panoramas of Streetview and Look Around?

**Comment by sk-zk** [comment]
I'm not entirely sure what you mean, but Streetside doesn't actually have metadata tiles like Street View and Look Around do; there's just an endpoint to retrieve panoramas by an arbitrary bounding box.
If you want to retrieve Streetside panoramas within the same area as a slippy map tile, you can calculate the equivalent bounding box as follows:

```
from streetlevel.geo import tile_coord_to_wgs84

def tile_coord_to_bbox(x: float, y: float, z: int) -> Tuple[float, float, float, float]:
    north, west = tile_coord_to_wgs84(x, y, z)
    south, east = tile_coord_to_wgs84(x+1, y+1, z)
    return north, west, south, east
```
